apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root_password: base64_encoded_root_password
  user_password: base64_encoded_user_password
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
data:
  secret_key: base64_encoded_secret_key
  sqlalchemy_uri: base64_encoded_sqlalchemy_uri
