apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root_password: cGFzc3dvcmQ=
  user_password: dXNlcg==
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
data:
  secret_key: dXNlcg==
  sqlalchemy_uri: bXlzcWwrcHlteXNxbDovL3VzZXI6cGFzc3dvcmRAZGIvc2Vuc29yZGI=
