apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: database
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None 
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: api
spec:
  selector:
    app: flask
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007