# Usar a imagem oficial do MySQL
FROM mysql:5.7

# Definir o diretório de trabalho dentro do container
WORKDIR /app/

# Listar os conteúdos de /app
RUN pwd

# Copiar os scripts SQL para o diretório que é executado durante a inicialização do container
COPY ./scripts/ /docker-entrypoint-initdb.d/
