# Usar a imagem oficial do MySQL
FROM mysql:5.7

RUN ls -l ./scripts

# Copiar os scripts SQL para o diretório que é executado durante a inicialização do container
COPY ./scripts/ /docker-entrypoint-initdb.d/
