version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    depends_on:
      - mysql-service
    environment:
        PYTHONUNBUFFERED: 0
        SQLALCHEMY_DATABASE_URI: mysql+pymysql://user:password@mysql-service/sensordb

  mysql-service:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sensordb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  db-data:
